# 配置端口
server:
  port: 8088
  servlet:
    #    context-path: /api
    application-display-name: demo

spring:
  application:
    name: demo
  profiles:
    active: dev
  # 配置数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false # MySQL在高版本需要指明是否进行SSL连接 解决则加上 &useSSL=false
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    #最大活动连接数
    maxActive: 20
    #初始化时创建的初始连接数
    initialSize: 1
    #当连接池耗尽时，连接池等待可用连接的最大时间
    maxWait: 60000
    #连接池中应保持的最小空闲连接数
    minIdle: 1
    #空闲连接清理线程运行的时间间隔
    timeBetweenEvictionRunsMillis: 60000
    #空闲连接清理线程运行的时间间隔
    minEvictableIdleTimeMillis: 300000
    #验证连接有效性的SQL查询语句
    validationQuery: select 'x'
    #验证连接有效性的SQL查询语句
    testWhileIdle: true
    #是否在从连接池借用连接时通过执行 validationQuery 来验证连接的有效性
    testOnBorrow: false
    #指定是否在将连接归还到连接池时通过执行 validationQuery 来验证连接的有效性
    testOnReturn: false
    #是否对预编译语句进行连接池化
    poolPreparedStatements: true
    #连接池中可以缓存的最大预编译语句数
    maxOpenPreparedStatements: 20
management:
  security:
    enabled: false

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:**/*Mapper.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: false
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: 0 # 逻辑已删除值(默认为 1)
    #logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
    #自定义填充策略接口实现
    #    meta-object-handler: com.zhengqing.config.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    #    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 解决oracle更新数据为null时无法转换报错，mysql不会出现此情况
    jdbc-type-for-null: 'null'
